# Data Stories

In [1]:
import plotly.graph_objs as go
import pandas as pd

In [29]:
life_expectancy_df = pd.read_csv('datasets_71509_948751_life_expectancy.csv').filter(items=["Neighborhood", "2010-2014", "Gender"])
life_expectancy_df

                                     Neighborhood  2010-2014  Gender
0                                        el Raval       85.3  Female
1                                  el Barri Gòtic       84.4  Female
2                                  la Barceloneta       84.7  Female
3           Sant Pere, Santa Caterina i la Ribera       85.3  Female
4                                   el Fort Pienc       86.7  Female
..                                            ...        ...     ...
141  Diagonal Mar i el Front Marítim del Poblenou       82.2    Male
142                         el Besòs i el Maresme       79.6    Male
143                       Provençals del Poblenou       81.5    Male
144                      Sant Martí de Provençals       80.2    Male
145                           la Verneda i la Pau       80.6    Male

[146 rows x 3 columns]

In [20]:
accidents_df = pd.read_csv('accidents_2017.csv')
accidents_df = accidents_df[accidents_df["Neighborhood Name"] != "Unknown"]
accidents_df

,Id,District Name,Neighborhood Name,Street,Weekday,Month,Day,Hour,Part of the day,Mild injuries,Serious injuries,Victims,Vehicles involved,Longitude,Latitude
4,2017S004615,Sant Martí,el Camp de l'Arpa del Clot,Las Navas de Tolosa ...,Thursday,May,25,14,Afternoon,1,0,1,3,2.185272,41.416365
5,2017S007775,Sant Martí,el Camp de l'Arpa del Clot,Indústria / Trinxant ...,Wednesday,September,20,12,Morning,1,0,1,2,2.183245,41.416336
6,2017S004484,Sant Martí,el Camp de l'Arpa del Clot,Trinxant / Indústria ...,Saturday,May,20,21,Afternoon,1,0,1,2,2.183245,41.416336
7,2017S010680,Sant Martí,el Camp de l'Arpa del Clot,Indústria ...,Tuesday,December,26,20,Afternoon,2,0,2,1,2.183561,41.416372
8,2017S005152,Sant Martí,el Camp de l'Arpa del Clot,Indústria ...,Monday,June,12,15,Afternoon,1,0,1,1,2.184059,41.416763
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10334,2017S003667,Sant Andreu,el Bon Pastor,Litoral (Llobregat) ...,Tuesday,April,25,8,Morning,1,0,1,3,2.201800,41.392004
10335,2017S001896,Sant Andreu,el Bon Pastor,PL MONTERREY ...,Wednesday,March,8,12,Morning,1,0,1,2,2.206013,41.443445
10336,2017S010718,Sant Andreu,el Bon Pastor,Litoral (Llobregat) ...,Thursday,December,28,8,Morning,1,0,1,2,2.205607,41.443894
10337,2017S006145,Sant Andreu,el Bon Pastor,Litoral (Besòs) ...,Friday,July,14,14,Afternoon,1,0,1,2,2.205118,41.444824
10338,2017S000178,Sant Andreu,el Bon Pastor,CIUTAT D'ASUNCIÓN ...,Sunday,January,8,20,Afternoon,0,0,0,1,2.200956,41.437125

In [50]:
districts_df = accidents_df.filter(items=['District Name', 'Neighborhood Name']).drop_duplicates()
districts_df

     District Name           Neighborhood Name
4       Sant Martí  el Camp de l'Arpa del Clot
35      Sant Martí                     el Clot
43      Sant Martí    Sant Martí de Provençals
63      Sant Martí         la Verneda i la Pau
64      Sant Martí       el Besòs i el Maresme
...            ...                         ...
1190   Sant Andreu                 Sant Andreu
1198   Sant Andreu                       Navas
1215   Sant Andreu           la Trinitat Vella
1219   Sant Andreu               Baró de Viver
1222   Sant Andreu               el Bon Pastor

[73 rows x 2 columns]

In [19]:
unemployment_df = pd.read_csv('unemployment.csv')
unemployment_df.head(5)
unemployment_df.groupby('District Name').count()

,Year,Month,District Code,Neighborhood Code,Neighborhood Name,Gender,Demand_occupation,Number
District Name,,,,,,,,
Ciutat Vella,768,768,768,768,768,768,768,768
Eixample,1152,1152,1152,1152,1152,1152,1152,1152
Gràcia,960,960,960,960,960,960,960,960
Horta-Guinardó,2112,2112,2112,2112,2112,2112,2112,2112
Les Corts,576,576,576,576,576,576,576,576
No consta,192,192,192,192,192,192,192,192
Nou Barris,2496,2496,2496,2496,2496,2496,2496,2496
Sant Andreu,1344,1344,1344,1344,1344,1344,1344,1344
Sant Martí,1920,1920,1920,1920,1920,1920,1920,1920
Sants-Montjuïc,1536,1536,1536,1536,1536,1536,1536,1536
Sarrià-Sant Gervasi,1152,1152,1152,1152,1152,1152,1152,1152

## Hallo

In [5]:
population = pd.read_csv('population.csv')
population.head(5)

,Year,District.Code,District.Name,Neighborhood.Code,Neighborhood.Name,Gender,Age,Number
0,2017,1,Ciutat Vella,1,el Raval,Male,0-4,224
1,2017,1,Ciutat Vella,2,el Barri Gòtic,Male,0-4,50
2,2017,1,Ciutat Vella,3,la Barceloneta,Male,0-4,43
3,2017,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Male,0-4,95
4,2017,2,Eixample,5,el Fort Pienc,Male,0-4,124

In [15]:
population.groupby("District.Name").count()

,Year,District.Code,Neighborhood.Code,Neighborhood.Name,Gender,Age,Number
District.Name,,,,,,,
Ciutat Vella,3840,3840,3840,3840,3840,3840,3840
Eixample,5760,5760,5760,5760,5760,5760,5760
Gràcia,4800,4800,4800,4800,4800,4800,4800
Horta-Guinardó,10560,10560,10560,10560,10560,10560,10560
Les Corts,2880,2880,2880,2880,2880,2880,2880
Nou Barris,12480,12480,12480,12480,12480,12480,12480
Sant Andreu,6720,6720,6720,6720,6720,6720,6720
Sant Martí,9600,9600,9600,9600,9600,9600,9600
Sants-Montjuïc,7680,7680,7680,7680,7680,7680,7680
Sarrià-Sant Gervasi,5760,5760,5760,5760,5760,5760,5760